use_frameworks!

platform :ios, '9.0'

target 'SwiftAccessObjcConstants_Example' do
  pod 'SwiftAccessObjcConstants', :path => '../'

  target 'SwiftAccessObjcConstants_Tests' do
    inherit! :search_paths

    
  end
end
